repos:
- repo: local
  hooks:
  - id: my-hook
    name: my-hook-name
    description: my-hook-description
    language: system
    files: 'run/out'
    types: [text]
    always_run: true
    entry: ./run/generate.sh
