repos:
- repo: local
  hooks:
  - id: gen-files
    name: Generate files
    language: system
    require_serial: true
    always_run: true
    entry: ./run/generate.sh

- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
  - id: git-dirty  # Configure in .gitignore